### ISSUE TITLE
High sierra ?

### ISSUE THREAD

**Issue by ut0mt8** [wallace-aph/osxrice#1]
Have you test on high sierra ?
Seems not working but don't know why exactly.
If you can take a look ?

**Comment by wallace-aph** [comment]
I haven't updated to High Sierra yet, does the folder you put the files into exist already? I don't know if they changed how macOS handles .car files. Try taking a screenshot with it installed and I'll take a look.

**Comment by mnk400** [comment]
Just crashes finder indefinitely if installed on High Sierra.

**Comment by wallace-aph** [comment]
Thanks for letting me know, I'll mark it as broken for High Sierra. Once I update to High Sierra myself, I'll get a working version out.

**Comment by ut0mt8** [comment]
I personally recommend high sierra. Good release so far and the new fs seems faster (and it come with encryption)

**Comment by wallace-aph** [comment]
Glad to hear it, I'm super excited for APFS, I just usually wait a few months for new releases to update so that the bugs are mostly gone. I'll get the tweak up once I update.
